<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Finance Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .container {
            max-width: 800px;
            margin: auto;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table th, table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table th {
            background-color: #f8f9fa;
        }
        .table-title-row {
            text-align: center;
            font-size: 1.2rem;
            font-weight: bold;
            padding: 5px;
        }
        .row {
            margin-bottom: 15px;
        }
        .row h6 {
            font-weight: bold;
        }
        .row p {
            margin: 5px 0;
        }
        .row div {
            display: inline-block;
            width: 48%;
        }
        .footer-message {
            text-align: center;
            margin-top: 30px;
            font-size: 0.9rem;
            color: #888;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="header">
            <h2>Project Finance Details</h2>
            <p>{{ $project->details->title ?? '' }}-{{ $project->unique_id }}</p>
        </div>

        <!-- Table Title Row -->
        <div class="table-title-row">
            Costs
        </div>

        <table>
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Cost Field</th>
                    <th>Cost Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($costs as $key => $cost)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $cost->field }}</td>
                        <td>{{ $cost->cost }} BDT</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p>Total Cost: {{ $totalCost }}</p>
        <p>Total Revenue: {{ $revenue }}</p>
        <p>Total Outcome: {{ $profit }}</p>
        <p>Service Charge: {{ $serviceChargePercent }}%</p>
        <p>Net Profit: {{ $netProfit }}</p>
        <p>Total Unit: {{ $unit }}</p>
        <p>Profit/Unit: {{ $profitPerUnit }}</p>

        <!-- Footer Message -->
        <div class="footer-message">
            PDF generated by My Krishi Software
        </div>

    </div>

</body>
</html>
